PREFIX :<http://www.ontotext.com/connectors/lucene#>
PREFIX inst:<http://www.ontotext.com/connectors/lucene/instance#>
INSERT DATA {
	inst:manifestationsIndex :createConnector '''
{
  "fields": [
    {
        "fieldName": "names$manifestation",
        "propertyChain": [
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/object/P00019"
         ]
    },
    
    {
        "fieldName": "names$expression",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "names$sourceexpression",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20574",
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "names$work",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "names$transformationof",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10337",
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "names$augmentationof",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10192",
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/object/P00019"
        ]
    },
    {
        "fieldName": "names$haspartwork",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10147",
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/datatype/P00019"
        ]
    },
        {
        "fieldName": "names$ispartwork",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10019",
            "http://rdaregistry.info/Elements/x/object/P00006",
            "http://rdaregistry.info/Elements/x/datatype/P00019"
        ]
    },
    {
        "fieldName": "titles$manifestation",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20059",
            "http://rdaregistry.info/Elements/x/object/P00019"
        ]
    },
    {
        "fieldName": "titles$expression",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "titles$sourceexpression",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20574",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "titles$work",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "titles$transformationof",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10337",
            "http://rdaregistry.info/Elements/x/P00019"
        ]
    },
    {
        "fieldName": "titles$augmentationof",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10192",
            "http://rdaregistry.info/Elements/x/object/P00019"
        ]
    },
    {
        "fieldName": "titles$haspartwork",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10147",
            "http://rdaregistry.info/Elements/x/datatype/P00019"
        ]
    },
    {
        "fieldName": "titles$ispartwork",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10019",
            "http://rdaregistry.info/Elements/x/datatype/P00019"
        ]
    },
    {
        "fieldName": "categories$carrier",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/P30002",
            "http://www.w3.org/2000/01/rdf-schema#label"
        ]
    },
    {
        "fieldName": "categories$mediatype",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30001",
            "http://www.w3.org/2000/01/rdf-schema#label"
        ]
    },
    {
        "fieldName": "categories$content",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20001",
            "http://www.w3.org/2000/01/rdf-schema#label"
        ]
    },
    {
        "fieldName": "categories$language",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20006",
            "http://www.w3.org/2000/01/rdf-schema#label"
        ]
    },
    {
        "fieldName": "categories$worktype",
        "propertyChain": [
            "http://rdaregistry.info/Elements/m/object/P30139",
            "http://rdaregistry.info/Elements/e/object/P20231",
            "http://rdaregistry.info/Elements/w/object/P10004",
            "http://www.w3.org/2000/01/rdf-schema#label"
        ]
    }
  ],
  "languages": [],
  "types": [
    "http://rdaregistry.info/Elements/c/C10007"
  ],
  "readonly": false,
  "detectFields": false,
  "importGraph": false,
  "skipInitialIndexing": false,
  "boostProperties": [],
  "stripMarkup": false
}
''' .
}
