PREFIX :<http://www.ontotext.com/connectors/lucene#>
PREFIX inst:<http://www.ontotext.com/connectors/lucene/instance#>
# Conditional drop: only fires if the connector already exists.
INSERT { inst:manifestationsIndex :dropConnector "" }
WHERE { inst:manifestationsIndex :connectorStatus ?status }
;
PREFIX :<http://www.ontotext.com/connectors/lucene#>
PREFIX inst:<http://www.ontotext.com/connectors/lucene/instance#>
# mediaType, carrierType, language, contentType, workType and genre hold
# category IRIs, not analyzed, for the search filters and their counts
# (lucene:facetFields). Language and content type come from the embodied
# expressions, work type and genre from their works (entedit:P01/P02); each
# link is followed from either side, and a field name with $ merges into the
# part before it. A manifestation counts once per value, however many of its
# expressions have it.
# expression and work hold the IRIs of the embodied expressions and their works,
# for following a link from a search result: the search is limited to the
# publications containing the linked expression or any expression of the
# linked work, and the label's words only rank the hits.
# titles$otherTitle adds other title information (subtitles, a volume's list
# of titles), which is not a subproperty of x:P00019. It is left out of the
# expressions index on purpose: there it would reach every expression the
# manifestation embodies, so a volume's other titles would match all its parts.
INSERT DATA {
	inst:manifestationsIndex :createConnector '''
{
  "fields": [
    {
      "fieldName": "names$manifestation",
      "propertyChain": [
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "names$expression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "names$sourceexpression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20574",
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "names$work",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "names$transformationof",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10337",
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "names$augmentationof",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10192",
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "names$haspartwork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10147",
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "names$ispartwork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10019",
        "http://rdaregistry.info/Elements/x/object/P00006",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$manifestation",
      "propertyChain": [
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$otherTitle",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/datatype/P30142"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$statementOfResponsibility",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/datatype/P30117"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$expression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$sourceexpression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20574",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$work",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$transformationof",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10337",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$augmentationof",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10192",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$haspartwork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10147",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "titles$ispartwork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10019",
        "http://rdaregistry.info/Elements/x/P00019"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$manifestation",
      "propertyChain": [
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$expression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$sourceexpression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20574",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$work",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$transformationof",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10337",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$augmentationof",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10192",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$haspartwork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10147",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "labels$ispartwork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10019",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "categories$carrier",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/P30002",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "categories$mediatype",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30001",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "categories$content",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20001",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "categories$language",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20006",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "categories$worktype",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://rdaregistry.info/Elements/w/object/P10004",
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "mediaType",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30002"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "carrierType",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30001"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "language$fromManifestation",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20006"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "language$fromExpression",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "http://rdaregistry.info/Elements/e/object/P20006"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "contentType$fromManifestation",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20001"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "contentType$fromExpression",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "http://rdaregistry.info/Elements/e/object/P20001"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "workType$fromManifestation_fromExpression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://oslomet.no/abi/vocab#P01"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "workType$fromManifestation_fromWork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "^http://rdaregistry.info/Elements/w/object/P10078",
        "http://oslomet.no/abi/vocab#P01"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "workType$fromExpression_fromExpression",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://oslomet.no/abi/vocab#P01"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "workType$fromExpression_fromWork",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "^http://rdaregistry.info/Elements/w/object/P10078",
        "http://oslomet.no/abi/vocab#P01"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "genre$fromManifestation_fromExpression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://oslomet.no/abi/vocab#P02"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "genre$fromManifestation_fromWork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "^http://rdaregistry.info/Elements/w/object/P10078",
        "http://oslomet.no/abi/vocab#P02"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "genre$fromExpression_fromExpression",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "http://rdaregistry.info/Elements/e/object/P20231",
        "http://oslomet.no/abi/vocab#P02"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "genre$fromExpression_fromWork",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "^http://rdaregistry.info/Elements/w/object/P10078",
        "http://oslomet.no/abi/vocab#P02"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": true
    },
    {
      "fieldName": "expression$fromManifestation",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    },
    {
      "fieldName": "expression$fromExpression",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    },
    {
      "fieldName": "work$fromManifestation_fromExpression",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "http://rdaregistry.info/Elements/e/object/P20231"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    },
    {
      "fieldName": "work$fromManifestation_fromWork",
      "propertyChain": [
        "http://rdaregistry.info/Elements/m/object/P30139",
        "^http://rdaregistry.info/Elements/w/object/P10078"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    },
    {
      "fieldName": "work$fromExpression_fromExpression",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "http://rdaregistry.info/Elements/e/object/P20231"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    },
    {
      "fieldName": "work$fromExpression_fromWork",
      "propertyChain": [
        "^http://rdaregistry.info/Elements/e/object/P20059",
        "^http://rdaregistry.info/Elements/w/object/P10078"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": true,
      "ignoreInvalidValues": false,
      "facet": false
    }
  ],
  "languages": [],
  "types": [
    "http://rdaregistry.info/Elements/c/C10007"
  ],
  "readonly": false,
  "detectFields": false,
  "importGraph": false,
  "skipInitialIndexing": false,
  "boostProperties": [],
  "stripMarkup": false
}
''' .
}
